apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml
  - rbac.yaml
  # Download official Traefik CRDs
  - https://raw.githubusercontent.com/traefik/traefik/v3.0/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - config.yaml
  - storage.yaml
  - deployment.yaml
  - services.yaml
  - ingress.yaml
  - ingressclass.yaml

labels:
  - pairs:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/part-of: homelab

images:
- name: traefik
  newTag: "3.0"