apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-data
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteMany  # RWX for multiple replicas
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 1Gi