apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-config
  namespace: code-server
  labels:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/part-of: homelab
data:
  # code-server configuration
  config.yaml: |
    bind-addr: 0.0.0.0:8080
    auth: password
    password: ""  # Will be set via environment variable
    cert: false
    disable-telemetry: true
    disable-update-check: true
    disable-file-downloads: false
    disable-workspace-trust: false
  
  # Default settings for VS Code
  settings.json: |
    {
      "workbench.colorTheme": "Default Dark+",
      "editor.fontSize": 14,
      "editor.fontFamily": "'Fira Code', 'Cascadia Code', 'JetBrains Mono', 'Consolas', 'Monaco', 'Courier New', monospace",
      "editor.fontLigatures": true,
      "editor.tabSize": 2,
      "editor.insertSpaces": true,
      "editor.detectIndentation": true,
      "editor.renderWhitespace": "boundary",
      "editor.rulers": [80, 120],
      "files.autoSave": "afterDelay",
      "files.autoSaveDelay": 1000,
      "terminal.integrated.fontSize": 13,
      "terminal.integrated.fontFamily": "'Fira Code', 'Cascadia Code', 'JetBrains Mono', 'Consolas', monospace",
      "git.confirmSync": false,
      "git.enableSmartCommit": true,
      "extensions.autoCheckUpdates": false,
      "extensions.autoUpdate": false,
      "telemetry.telemetryLevel": "off",
      "update.mode": "none"
    }