apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: code-server

resources:
  - namespace.yaml
  - configmap.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: code-server
      app.kubernetes.io/part-of: homelab

images:
- name: codercom/code-server
  newTag: "4.23.1"