# Copy this to secret.yaml and set your password
# The secret.yaml file is gitignored for security
apiVersion: v1
kind: Secret
metadata:
  name: code-server-auth
  namespace: code-server
  labels:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/part-of: homelab
type: Opaque
stringData:
  # Set a strong password for code-server access
  PASSWORD: "your-secure-password-here"
  
  # Optional: Add SSH keys for Git operations
  # ssh-privatekey: |
  #   -----BEGIN OPENSSH PRIVATE KEY-----
  #   your-ssh-private-key-here
  #   -----END OPENSSH PRIVATE KEY-----
  # ssh-publickey: "ssh-rsa your-public-key-here"