apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-data
  namespace: code-server
  labels:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-projects
  namespace: code-server
  labels:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 20Gi