apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config-new
  namespace: automation
  labels:
    app.kubernetes.io/name: overseerr
    migrated: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 2Gi