# Master Configuration File for Ultimate Life Automation Platform
# This file contains all user-specific configurations required for a turnkey deployment
# Values marked as REQUIRED must be filled before deployment

# DNS and Domain Configuration
domain:
  base: "k8s.dttesting.com"  # Base domain for all services
  email: "admin@dttesting.com"  # REQUIRED: Email for Let's Encrypt certificates

# Cloudflare Configuration (for DNS-01 challenges)
cloudflare:
  email: "motoyuki85@gmail.com"  # REQUIRED: Cloudflare account email
  api_token: "your-cloudflare-api-token"  # REQUIRED: Cloudflare API token with Zone:Read and DNS:Edit permissions
  zone_id: "458be0a82a2c"  # OPTIONAL: Can be auto-discovered from domain

# VPN Configuration (Gluetun)
vpn:
  provider: "surfshark"  # REQUIRED: VPN provider (surfshark, nordvpn, expressvpn, etc.)
  username: "your-vpn-username"  # REQUIRED: VPN account username
  password: "your-vpn-password"  # REQUIRED: VPN account password
  server_regions: "Netherlands"  # OPTIONAL: Preferred server regions
  port_forwarding: false  # Enable if your VPN supports it

# Media Management Configuration
media:
  # Paths (these are inside containers, mapped to NFS)
  tv_path: "/media/tv"
  movies_path: "/media/movies"
  music_path: "/media/music"
  books_path: "/media/books"
  downloads_path: "/downloads"
  
  # Quality Profiles
  quality_profiles:
    tv: "WEBDL-1080p"
    movies: "WEBDL-1080p"
    music: "FLAC"
    books: "EPUB"

# Download Client Configuration
downloads:
  # qBittorrent
  qbittorrent:
    admin_password: "changeme123!"  # REQUIRED: Change this!
    port: 8080
    
  # NZBget
  nzbget:
    admin_password: "changeme123!"  # REQUIRED: Change this!
    port: 6789
    
  # Usenet Provider (for NZBget)
  usenet:
    host: "news.provider.com"  # REQUIRED if using Usenet
    port: 563
    username: "your-usenet-username"  # REQUIRED if using Usenet
    password: "your-usenet-password"  # REQUIRED if using Usenet
    connections: 20

# Indexer Configuration (Prowlarr)
indexers:
  # Add your indexer API keys here
  # Example:
  # - name: "NZBgeek"
  #   api_key: "your-api-key"
  # - name: "NZBFinder"
  #   api_key: "your-api-key"

# Notification Configuration
notifications:
  # Notifiarr
  notifiarr:
    api_key: "your-notifiarr-api-key"  # REQUIRED: Get from notifiarr.com
    
  # Discord
  discord:
    webhook_url: "https://discord.com/api/webhooks/..."  # REQUIRED for Discord notifications
    
  # Other notification services can be added here

# Document Management Configuration
paperless:
  admin_password: "changeme123!"  # REQUIRED: Change this!
  secret_key: "change-this-to-a-long-random-string"  # REQUIRED: Generate a secure key
  postgres_password: "paperless-db-password"  # REQUIRED: Database password
  redis_password: "paperless-redis-password"  # OPTIONAL: Redis password if needed
  ocr_languages: "eng"  # Languages for OCR (eng, deu, fra, etc.)
  time_zone: "America/Chicago"  # Your timezone

# Household Management Configuration
grocy:
  culture: "en_US"  # Locale setting
  currency: "USD"  # Currency code
  energy_unit: "kcal"  # Energy unit (kcal or kJ)
  # Authentication will be configured post-deployment

# Monitoring Configuration
monitoring:
  # Grafana
  grafana:
    admin_password: "changeme123!"  # REQUIRED: Change this!
    
  # Prometheus (usually no auth needed for internal use)
  retention_days: 30  # How long to keep metrics

# Development Environment
code_server:
  password: "changeme123!"  # REQUIRED: Password for VS Code access
  sudo_password: "changeme123!"  # REQUIRED: Sudo password in terminal

# Container Management
portainer:
  # Admin account created on first login
  # No pre-configuration needed

# Service Dashboard
homer:
  # Configuration is done via web interface
  # No pre-configuration needed

# ArgoCD GitOps
argocd:
  admin_password: "changeme123!"  # REQUIRED: Change this!
  github_repo: "https://github.com/yourusername/k8s-homelab-migration"  # Your repo URL
  github_token: ""  # OPTIONAL: For private repos

# Remote Desktop
rustdesk:
  # Relay configuration
  relay_password: "changeme123!"  # REQUIRED: Change this!
  
# Storage Configuration
storage:
  nfs_server: "192.168.1.10"  # REQUIRED: Your NFS server IP
  nfs_path: "/mnt/storage"  # REQUIRED: Base NFS export path

# Network Configuration
network:
  metallb_ip_range: "192.168.1.200-192.168.1.239"  # LoadBalancer IP range
  cluster_vip: "192.168.1.240"  # Kubernetes API VIP
  
# Security Settings
security:
  # Generate strong passwords for production use!
  # You can use: openssl rand -base64 32
  default_admin_password: "changeme123!"  # NEVER use this in production!