apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.2/manifests/install.yaml
  - ingress.yaml

patches:
  - path: server-service-patch.yaml
    target:
      kind: Service
      name: argocd-server
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --insecure
    target:
      kind: Deployment
      name: argocd-server