apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notifications

resources:
  - namespace.yaml
  - secrets.yaml
  - storage.yaml
  - notifiarr-deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: notifiarr
      app.kubernetes.io/part-of: homelab

images:
- name: golift/notifiarr
  newTag: "latest"