apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifiarr
  namespace: notifications
  labels:
    app.kubernetes.io/name: notifiarr
    app.kubernetes.io/component: notification-hub
    app.kubernetes.io/part-of: homelab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: notifiarr
      app.kubernetes.io/component: notification-hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notifiarr
        app.kubernetes.io/component: notification-hub
        app.kubernetes.io/part-of: homelab
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
      containers:
      - name: notifiarr
        image: golift/notifiarr:latest
        env:
        # Notifiarr API Configuration
        - name: DN_API_KEY
          valueFrom:
            secretKeyRef:
              name: notifiarr-secrets
              key: DN_API_KEY
        
        # Basic Configuration
        - name: DN_DEBUG
          value: "false"
        - name: DN_QUIET
          value: "false"
        - name: DN_LOG_FILE
          value: "/config/logs/notifiarr.log"
        - name: DN_LOG_FILES
          value: "10"
        - name: DN_LOG_FILE_MB
          value: "100"
        
        # Web UI Configuration
        - name: DN_UI_PASSWORD
          value: "notifiarr123!"
        - name: DN_BIND_ADDR
          value: "0.0.0.0:5454"
        
        # Timezone
        - name: TZ
          value: "America/New_York"
        
        # *arr Applications Configuration
        - name: DN_SONARR_0_URL
          value: "http://sonarr.media.svc.cluster.local:8989"
        - name: DN_SONARR_0_API_KEY
          value: "get-from-sonarr-settings"
        - name: DN_SONARR_0_NAME
          value: "Sonarr"
        
        - name: DN_RADARR_0_URL
          value: "http://radarr.media.svc.cluster.local:7878"
        - name: DN_RADARR_0_API_KEY
          value: "get-from-radarr-settings"
        - name: DN_RADARR_0_NAME
          value: "Radarr"
        
        - name: DN_LIDARR_0_URL
          value: "http://lidarr.media.svc.cluster.local:8686"
        - name: DN_LIDARR_0_API_KEY
          value: "get-from-lidarr-settings"
        - name: DN_LIDARR_0_NAME
          value: "Lidarr"
        
        - name: DN_READARR_0_URL
          value: "http://readarr.media.svc.cluster.local:8787"
        - name: DN_READARR_0_API_KEY
          value: "get-from-readarr-settings"
        - name: DN_READARR_0_NAME
          value: "Readarr"
        
        # Download Clients Configuration
        - name: DN_QBITTORRENT_0_URL
          value: "http://qbittorrent.downloads.svc.cluster.local:8080"
        - name: DN_QBITTORRENT_0_USER
          value: "admin"
        - name: DN_QBITTORRENT_0_PASS
          value: "get-from-qbittorrent-config"
        - name: DN_QBITTORRENT_0_NAME
          value: "qBittorrent"
        
        - name: DN_NZBGET_0_URL
          value: "http://nzbget.downloads.svc.cluster.local:6789"
        - name: DN_NZBGET_0_USER
          value: "admin"
        - name: DN_NZBGET_0_PASS
          value: "admin123!"
        - name: DN_NZBGET_0_NAME
          value: "NZBget"
        
        # Plex Configuration (if available)
        - name: DN_PLEX_0_URL
          value: "http://your-plex-server:32400"
        - name: DN_PLEX_0_TOKEN
          value: "get-your-plex-token"
        - name: DN_PLEX_0_NAME
          value: "Plex"
        
        # Tautulli Configuration (if available)
        - name: DN_TAUTULLI_0_URL
          value: "http://your-tautulli:8181"
        - name: DN_TAUTULLI_0_API_KEY
          value: "get-from-tautulli"
        - name: DN_TAUTULLI_0_NAME
          value: "Tautulli"
        
        # Discord webhook (optional)
        - name: DN_DISCORD_WEBHOOK
          valueFrom:
            secretKeyRef:
              name: notifiarr-secrets
              key: DN_DISCORD_WEBHOOK
              optional: true
        
        # Telegram settings (optional)
        - name: DN_TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: notifiarr-secrets
              key: DN_TELEGRAM_TOKEN
              optional: true
        - name: DN_TELEGRAM_CHAT_ID
          valueFrom:
            secretKeyRef:
              name: notifiarr-secrets
              key: DN_TELEGRAM_CHAT_ID
              optional: true
        
        ports:
        - name: http
          containerPort: 5454
          protocol: TCP
        
        volumeMounts:
        - name: notifiarr-config
          mountPath: /config
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      
      volumes:
      - name: notifiarr-config
        persistentVolumeClaim:
          claimName: notifiarr-config
      
      nodeSelector:
        kubernetes.io/os: linux