apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifiarr-config
  namespace: notifications
  labels:
    app.kubernetes.io/name: notifiarr
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 1Gi