apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
  - namespace.yaml
  - paperless-secrets.yaml
  - postgres-storage.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - paperless-storage.yaml
  - paperless-deployment.yaml
  - paperless-service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: paperless-ngx
      app.kubernetes.io/part-of: homelab

images:
- name: postgres
  newName: postgres
  newTag: "15-alpine"
- name: redis
  newName: redis
  newTag: "7-alpine"
- name: ghcr.io/paperless-ngx/paperless-ngx
  newTag: "2.6.3"