apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: paperless
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: paperless-ngx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 10Gi