apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustdesk-hbbr
  namespace: rustdesk
  labels:
    app.kubernetes.io/name: rustdesk-hbbr
    app.kubernetes.io/component: relay-server
    app.kubernetes.io/part-of: rustdesk
spec:
  replicas: 1
  strategy:
    type: Recreate  # Since we need persistent storage
  selector:
    matchLabels:
      app.kubernetes.io/name: rustdesk-hbbr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rustdesk-hbbr
        app.kubernetes.io/component: relay-server
        app.kubernetes.io/part-of: rustdesk
    spec:
      containers:
      - name: hbbr
        image: rustdesk/rustdesk-server:latest
        command: ["hbbr"]
        ports:
        - name: relay
          containerPort: 21117
          protocol: TCP
        - name: web-client-2
          containerPort: 21119
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /root
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 21117
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 21117
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rustdesk-hbbr-data