apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustdesk-hbbs
  namespace: rustdesk
  labels:
    app.kubernetes.io/name: rustdesk-hbbs
    app.kubernetes.io/component: id-server
    app.kubernetes.io/part-of: rustdesk
spec:
  replicas: 1
  strategy:
    type: Recreate  # Since we need persistent storage
  selector:
    matchLabels:
      app.kubernetes.io/name: rustdesk-hbbs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rustdesk-hbbs
        app.kubernetes.io/component: id-server
        app.kubernetes.io/part-of: rustdesk
    spec:
      containers:
      - name: hbbs
        image: rustdesk/rustdesk-server:latest
        command: ["hbbs"]
        args: ["-r", "rustdesk-hbbr.rustdesk.svc.cluster.local"]
        ports:
        - name: nat-test
          containerPort: 21115
          protocol: TCP
        - name: id-reg
          containerPort: 21116
          protocol: TCP
        - name: id-reg-udp
          containerPort: 21116
          protocol: UDP
        - name: web-client
          containerPort: 21118
          protocol: TCP
        env:
        - name: ALWAYS_USE_RELAY
          value: "Y"
        volumeMounts:
        - name: data
          mountPath: /root
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 21116
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 21116
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rustdesk-hbbs-data