apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rustdesk

resources:
  - namespace.yaml
  - local-storage.yaml
  - storage.yaml
  - hbbs-deployment.yaml
  - hbbr-deployment.yaml
  - services.yaml

labels:
  - pairs:
      app.kubernetes.io/name: rustdesk
      app.kubernetes.io/part-of: homelab

images:
- name: rustdesk/rustdesk-server
  newTag: latest