apiVersion: v1
kind: PersistentVolume
metadata:
  name: rustdesk-hbbs-pv
  labels:
    app.kubernetes.io/name: rustdesk-hbbs
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: rustdesk
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/rustdesk/hbbs
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - talos-worker-01  # Pin to specific worker node
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rustdesk-hbbr-pv
  labels:
    app.kubernetes.io/name: rustdesk-hbbr
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: rustdesk
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/rustdesk/hbbr
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - talos-worker-01  # Pin to specific worker node