apiVersion: v1
kind: Service
metadata:
  name: rustdesk-hbbs
  namespace: rustdesk
  labels:
    app.kubernetes.io/name: rustdesk-hbbs
    app.kubernetes.io/component: id-server
    app.kubernetes.io/part-of: rustdesk
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.201  # Request specific IP from MetalLB pool
  ports:
  - name: nat-test
    port: 21115
    targetPort: 21115
    protocol: TCP
  - name: id-reg-tcp
    port: 21116
    targetPort: 21116
    protocol: TCP
  - name: id-reg-udp
    port: 21116
    targetPort: 21116
    protocol: UDP
  - name: web-client
    port: 21118
    targetPort: 21118
    protocol: TCP
  selector:
    app.kubernetes.io/name: rustdesk-hbbs
---
apiVersion: v1
kind: Service
metadata:
  name: rustdesk-hbbr
  namespace: rustdesk
  labels:
    app.kubernetes.io/name: rustdesk-hbbr
    app.kubernetes.io/component: relay-server
    app.kubernetes.io/part-of: rustdesk
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.202  # Request specific IP from MetalLB pool
  ports:
  - name: relay
    port: 21117
    targetPort: 21117
    protocol: TCP
  - name: web-client-2
    port: 21119
    targetPort: 21119
    protocol: TCP
  selector:
    app.kubernetes.io/name: rustdesk-hbbr
---
apiVersion: v1
kind: Service
metadata:
  name: rustdesk-hbbs-cluster
  namespace: rustdesk
  labels:
    app.kubernetes.io/name: rustdesk-hbbs
    app.kubernetes.io/component: id-server
    app.kubernetes.io/part-of: rustdesk
spec:
  type: ClusterIP
  ports:
  - name: nat-test
    port: 21115
    targetPort: 21115
    protocol: TCP
  - name: id-reg-tcp
    port: 21116
    targetPort: 21116
    protocol: TCP
  - name: web-client
    port: 21118
    targetPort: 21118
    protocol: TCP
  selector:
    app.kubernetes.io/name: rustdesk-hbbs
---
apiVersion: v1
kind: Service
metadata:
  name: rustdesk-hbbr-cluster
  namespace: rustdesk
  labels:
    app.kubernetes.io/name: rustdesk-hbbr
    app.kubernetes.io/component: relay-server
    app.kubernetes.io/part-of: rustdesk
spec:
  type: ClusterIP
  ports:
  - name: relay
    port: 21117
    targetPort: 21117
    protocol: TCP
  - name: web-client-2
    port: 21119
    targetPort: 21119
    protocol: TCP
  selector:
    app.kubernetes.io/name: rustdesk-hbbr