apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-hbbs-data
  namespace: rustdesk
  labels:
    app.kubernetes.io/name: rustdesk-hbbs
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: rustdesk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # Use default (local) storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-hbbr-data
  namespace: rustdesk
  labels:
    app.kubernetes.io/name: rustdesk-hbbr
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: rustdesk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # Use default (local) storage
  resources:
    requests:
      storage: 1Gi