apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portainer

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: portainer
      app.kubernetes.io/part-of: homelab

images:
- name: portainer/portainer-ce
  newTag: latest