apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation

resources:
  - namespace.yaml
  - storage.yaml
  - prowlarr-deployment.yaml
  - overseerr-deployment.yaml
  - flaresolverr-deployment.yaml
  - services.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: indexers-automation
      app.kubernetes.io/part-of: homelab

images:
- name: lscr.io/linuxserver/prowlarr
  newTag: "develop"
- name: lscr.io/linuxserver/overseerr
  newTag: "latest"
- name: ghcr.io/flaresolverr/flaresolverr
  newTag: "latest"