apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: automation
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: indexers-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
  namespace: automation
  labels:
    app.kubernetes.io/name: overseerr
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: indexers-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 2Gi