apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
  namespace: homer
data:
  config.yml: |
    ---
    # Homepage configuration
    title: "Homelab Dashboard"
    subtitle: "k8s.dttesting.com"
    logo: "logo.png"
    icon: "fas fa-skull-crossbones"

    header: true
    footer: '<p>Powered by <a href="https://k8s.io">Kubernetes</a> • <a href="https://argo-cd.readthedocs.io">ArgoCD</a></p>'

    # Optional theme
    theme: default
    colors:
      light:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#f5f5f5"
        card-background: "#ffffff"
        text: "#363636"
        text-header: "#ffffff"
        text-title: "#303030"
        text-subtitle: "#424242"
        card-shadow: rgba(0, 0, 0, 0.1)
        link-hover: "#363636"
      dark:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#131313"
        card-background: "#2b2b2b"
        text: "#eaeaea"
        text-header: "#ffffff"
        text-title: "#fafafa"
        text-subtitle: "#f5f5f5"
        card-shadow: rgba(0, 0, 0, 0.4)
        link-hover: "#ffdd57"

    # Services
    services:
      - name: "Infrastructure"
        icon: "fas fa-cogs"
        items:
          - name: "ArgoCD"
            logo: "https://raw.githubusercontent.com/argoproj/argo-cd/master/docs/assets/logo.png"
            subtitle: "GitOps CD"
            tag: "app"
            url: "https://argocd.k8s.dttesting.com"
            target: "_blank"
          - name: "Kubernetes Dashboard"
            logo: "https://raw.githubusercontent.com/kubernetes/dashboard/master/docs/images/kubernetes-logo.png"
            subtitle: "Cluster Dashboard"
            tag: "app"
            url: "#"
            target: "_blank"

      - name: "Monitoring"
        icon: "fas fa-chart-line"
        items:
          - name: "Grafana"
            logo: "https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg"
            subtitle: "Metrics Dashboard"
            tag: "monitoring"
            url: "#"
            target: "_blank"
          - name: "Prometheus"
            logo: "https://raw.githubusercontent.com/prometheus/prometheus/main/web/ui/mantine-ui/public/prometheus-logo.svg"
            subtitle: "Metrics Collection"
            tag: "monitoring"  
            url: "#"
            target: "_blank"

      - name: "Media"
        icon: "fas fa-photo-video"
        items:
          - name: "Plex"
            logo: "https://www.plex.tv/wp-content/themes/plex/assets/img/plex-logo.svg"
            subtitle: "Media Server"
            tag: "media"
            url: "#"
            target: "_blank"
          - name: "Jellyfin"
            logo: "https://jellyfin.org/images/logo.svg"
            subtitle: "Media Server"
            tag: "media"
            url: "#"
            target: "_blank"