apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homer

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: homer
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: homelab