apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: household

resources:
  - namespace.yaml
  - storage.yaml
  - grocy-deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: grocy
      app.kubernetes.io/part-of: homelab

images:
- name: lscr.io/linuxserver/grocy
  newTag: "latest"