apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: downloads
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: download-clients
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: downloads
  labels:
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: download-clients
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-storage
  namespace: downloads
  labels:
    app.kubernetes.io/name: downloads-storage
    app.kubernetes.io/component: shared
    app.kubernetes.io/part-of: download-clients
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 5Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: incomplete-downloads
  namespace: downloads
  labels:
    app.kubernetes.io/name: incomplete-downloads
    app.kubernetes.io/component: temporary
    app.kubernetes.io/part-of: download-clients
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 2Ti