apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd-image-updater
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: homelab
data:
  # ArgoCD server connection configuration
  argocd.server_addr: "argocd-server.argocd.svc.cluster.local:443"
  argocd.insecure: "true"
  argocd.plaintext: "false"
  argocd.namespace: "argocd"
  
  # Log level
  log.level: "info"
  
  # Registry configuration
  registries.conf: |
    registries:
    - name: Docker Hub
      prefix: docker.io
      api_url: https://registry-1.docker.io
      credentials: pullsecret:default/regcred
      ping: yes
      
    - name: GitHub Container Registry
      prefix: ghcr.io
      api_url: https://ghcr.io
      ping: yes
      
    - name: Quay
      prefix: quay.io
      api_url: https://quay.io
      ping: yes
  
  # Git configuration for updating manifests
  git.user: "argocd-image-updater"
  git.email: "argocd-image-updater@homelab.local"
  
  # Applications to monitor (we'll add annotations to apps instead)
  applications: ""