apiVersion: v1
kind: Service
metadata:
  name: argocd-image-updater
  namespace: argocd-image-updater
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/component: image-updater
    app.kubernetes.io/part-of: homelab
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-image-updater