apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-config
  namespace: gluetun
  labels:
    app.kubernetes.io/name: gluetun
    app.kubernetes.io/part-of: homelab
data:
  # VPN Provider (examples: nordvpn, expressvpn, surfshark, pia, mullvad, etc.)
  VPN_SERVICE_PROVIDER: "private internet access"
  
  # VPN Type (wireguard or openvpn)
  # Using OpenVPN for PIA - WireGuard requires manual token generation
  VPN_TYPE: "openvpn"
  
  # Firewall settings
  FIREWALL: "on"
  # OpenVPN uses different port than WireGuard
  FIREWALL_VPN_INPUT_PORTS: "1198"
  
  # DNS settings  
  DOT: "on"
  DOT_PROVIDERS: "cloudflare"
  
  # Health check
  HEALTH_SERVER_ADDRESS: ":9999"
  
  # Logging
  LOG_LEVEL: "info"
  
  # Time zone
  TZ: "America/Los_Angeles"
  
  # Kill switch - blocks traffic if VPN disconnects
  FIREWALL_OUTBOUND_SUBNETS: "192.168.1.0/24,10.0.0.0/8,172.16.0.0/12"
  
  # Enable Shadowsocks (SOCKS5 proxy)
  SHADOWSOCKS: "on"
  SHADOWSOCKS_PASSWORD: "gluetun"
  SHADOWSOCKS_CIPHER: "chacha20-ietf-poly1305"
  
  # Enable HTTP proxy
  HTTPPROXY: "on"
  HTTPPROXY_STEALTH: "off"
  
  # Enable port forwarding for PIA (useful for torrenting)
  VPN_PORT_FORWARDING: "on"
  VPN_PORT_FORWARDING_PROVIDER: "private internet access"