apiVersion: v1
kind: Namespace
metadata:
  name: gluetun
  labels:
    app.kubernetes.io/name: gluetun
    app.kubernetes.io/part-of: homelab
    # Required for VPN containers that need NET_ADMIN and hostPath access
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged