# Copy this to secret.yaml and replace with your VPN credentials
# The secret.yaml file is gitignored for security
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-vpn-secret
  namespace: gluetun
  labels:
    app.kubernetes.io/name: gluetun
    app.kubernetes.io/part-of: homelab
type: Opaque
stringData:
  # For Mullvad (example)
  WIREGUARD_PRIVATE_KEY: "REPLACE_WITH_YOUR_WIREGUARD_PRIVATE_KEY"
  
  # For username/password VPN providers (e.g., NordVPN, ExpressVPN)
  # VPN_USERNAME: "your-username"
  # VPN_PASSWORD: "your-password"
  
  # For Mullvad specifically
  # WIREGUARD_ADDRESSES: "10.x.x.x/32"
  
  # For other providers, check gluetun documentation for required fields