apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-data
  namespace: gluetun
  labels:
    app.kubernetes.io/name: gluetun
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-apps
  resources:
    requests:
      storage: 1Gi