# VPN Provider Credentials Secret Template
# 
# This secret contains credentials for your VPN provider.
# Replace the placeholder values with your actual VPN credentials.
#
# Supported VPN Providers:
# - Private Internet Access (PIA): Use "private internet access" with spaces
# - AirVPN: Requires certificates from .ovpn files
# - Surfshark, ExpressVPN, NordVPN, and many others
# 
# Full list: https://github.com/qdm12/gluetun/wiki
#
apiVersion: v1
kind: Secret
metadata:
  name: pia-credentials  # or vpn-credentials for other providers
  namespace: gluetun
type: Opaque
stringData:
  # For Private Internet Access (PIA) - OpenVPN
  username: "p1234567"  # CONFIGURE: Your PIA username (p-number)
  password: "your-pia-password"  # CONFIGURE: Your PIA password
  
  # For AirVPN - requires certificates from .ovpn file
  # username: "your-airvpn-username"
  # password: "your-airvpn-password"
  # ca.crt: |
  #   -----BEGIN CERTIFICATE-----
  #   # Extract from .ovpn file between <ca> tags
  #   -----END CERTIFICATE-----
  # client.crt: |
  #   -----BEGIN CERTIFICATE-----
  #   # Extract from .ovpn file between <cert> tags
  #   -----END CERTIFICATE-----
  # client.key: |
  #   -----BEGIN PRIVATE KEY-----
  #   # Extract from .ovpn file between <key> tags
  #   -----END PRIVATE KEY-----
  
  # For WireGuard providers
  # WIREGUARD_PRIVATE_KEY: "your-wireguard-private-key"
  # WIREGUARD_PRESHARED_KEY: "your-wireguard-preshared-key"  # if required
  # WIREGUARD_ADDRESSES: "10.0.0.2/32"  # if required