apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/namespaces.yaml
  - kube-proxy/      # Deploy kube-proxy first for service routing
  - nfs-csi/
  - metallb/
  - ingress-nginx/
  - cert-manager/