apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/part-of: homelab
  annotations:
    # Enable automatic image updates
    argocd-image-updater.argoproj.io/image-list: "code-server=codercom/code-server"
    argocd-image-updater.argoproj.io/update-strategy: "semver:^4.0.0"
    argocd-image-updater.argoproj.io/write-back-method: "git"
    argocd-image-updater.argoproj.io/git-commit-message: "chore: update code-server image to {{.NewTag}} 🤖"
spec:
  project: default
  source:
    repoURL: https://github.com/machjesusmoto/k8s-homelab-migration.git
    targetRevision: main
    path: kubernetes/apps/code-server
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true