apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: indexers-automation
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: indexers-automation
    app.kubernetes.io/part-of: homelab
  annotations:
    # Enable automatic image updates
    argocd-image-updater.argoproj.io/image-list: "prowlarr=lscr.io/linuxserver/prowlarr,overseerr=lscr.io/linuxserver/overseerr,flaresolverr=ghcr.io/flaresolverr/flaresolverr"
    argocd-image-updater.argoproj.io/update-strategy: "latest,latest,latest"
    argocd-image-updater.argoproj.io/write-back-method: "git"
    argocd-image-updater.argoproj.io/git-commit-message: "chore: update indexers and automation images 🔍"
spec:
  project: default
  source:
    repoURL: https://github.com/machjesusmoto/k8s-homelab-migration.git
    targetRevision: main
    path: kubernetes/apps/indexers-automation
  destination:
    server: https://kubernetes.default.svc
    namespace: automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true