apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - core-infrastructure.yaml
  - homer.yaml
  - rustdesk.yaml
  - portainer.yaml
  - traefik.yaml
  - gluetun.yaml
  - argocd-image-updater.yaml
  - code-server.yaml
  - monitoring.yaml
  - paperless-ngx.yaml
  - media-management.yaml
  - download-clients.yaml
  - indexers-automation.yaml
  - notifiarr.yaml
  - grocy.yaml
