apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-management
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: media-management
    app.kubernetes.io/part-of: homelab
  annotations:
    # Enable automatic image updates
    argocd-image-updater.argoproj.io/image-list: "sonarr=lscr.io/linuxserver/sonarr,radarr=lscr.io/linuxserver/radarr,lidarr=lscr.io/linuxserver/lidarr,bazarr=lscr.io/linuxserver/bazarr,readarr=lscr.io/linuxserver/readarr"
    argocd-image-updater.argoproj.io/update-strategy: "latest,latest,latest,latest,latest"
    argocd-image-updater.argoproj.io/write-back-method: "git"
    argocd-image-updater.argoproj.io/git-commit-message: "chore: update media management stack images 🎬"
spec:
  project: default
  source:
    repoURL: https://github.com/machjesusmoto/k8s-homelab-migration.git
    targetRevision: main
    path: kubernetes/apps/media-management
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true