apiVersion: v1
kind: Namespace
metadata:
  name: cert-test
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-dttesting-com
  namespace: cert-test
spec:
  secretName: test-dttesting-com-tls
  issuerRef:
    name: letsencrypt-staging  # Using staging to avoid rate limits during testing
    kind: ClusterIssuer
  dnsNames:
  - test.k8s.dttesting.com