apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-csi

resources:
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.9.0/deploy/v4.9.0/rbac-csi-nfs.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.9.0/deploy/v4.9.0/csi-nfs-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.9.0/deploy/v4.9.0/csi-nfs-node.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.9.0/deploy/v4.9.0/csi-nfs-driverinfo.yaml