apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: stor1-truenasprod1.dttesting.com
  share: /mnt/rz3_storage/primary_dataset/media
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - vers=4.2
  - proto=tcp
  - timeo=600
  - retrans=2
  - hard
  - rsize=32768
  - wsize=32768
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-media
provisioner: nfs.csi.k8s.io
parameters:
  server: stor1-truenasprod1.dttesting.com
  share: /mnt/rz3_storage/primary_dataset/media
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - vers=4.2
  - proto=tcp
  - timeo=600
  - retrans=2
  - hard
  - rsize=32768
  - wsize=32768
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-apps
provisioner: nfs.csi.k8s.io
parameters:
  server: stor1-truenasprod1.dttesting.com
  share: /mnt/rz3_storage/primary_dataset/media/k8s-apps
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - vers=4.2
  - proto=tcp
  - timeo=600
  - retrans=2
  - hard
  - rsize=32768
  - wsize=32768